//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogSitesi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;
    public partial class User
    {
        public int KullaniciID { get; set; }
        public string KullaniciAdi { get; set; }
        public string Sifre { get; set; }
        public string Profil { get; set; }
        public string LoginErrorMessage { get; set; }
        public string TekrarSifre { get; set; }
        public string YeniSifre { get; set; }
        public virtual ICollection<Blog> Blogs { get; set; }
        public HttpPostedFileBase Imagefile { get; set; }
    }
}
